package com.dqbz.model;

import java.util.Date;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.BEGIN_TIME
     *
     * @mbggenerated
     */
    private String beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.END_TIME
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.INPUT_TIME
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.INPUT_USER
     *
     * @mbggenerated
     */
    private String inputUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.ID
     *
     * @return the value of event.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.ID
     *
     * @param id the value for event.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.TITLE
     *
     * @return the value of event.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.TITLE
     *
     * @param title the value for event.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.BEGIN_TIME
     *
     * @return the value of event.BEGIN_TIME
     *
     * @mbggenerated
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.BEGIN_TIME
     *
     * @param beginTime the value for event.BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.END_TIME
     *
     * @return the value of event.END_TIME
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.END_TIME
     *
     * @param endTime the value for event.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.INPUT_TIME
     *
     * @return the value of event.INPUT_TIME
     *
     * @mbggenerated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.INPUT_TIME
     *
     * @param inputTime the value for event.INPUT_TIME
     *
     * @mbggenerated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.INPUT_USER
     *
     * @return the value of event.INPUT_USER
     *
     * @mbggenerated
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.INPUT_USER
     *
     * @param inputUser the value for event.INPUT_USER
     *
     * @mbggenerated
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.UPDATE_TIME
     *
     * @return the value of event.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.UPDATE_TIME
     *
     * @param updateTime the value for event.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.UPDATE_USER
     *
     * @return the value of event.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.UPDATE_USER
     *
     * @param updateUser the value for event.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.CONTENT
     *
     * @return the value of event.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.CONTENT
     *
     * @param content the value for event.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}