package com.dqbz.model;

import java.util.Date;

public class Sweep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.MEMBERID
     *
     * @mbggenerated
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.cusName
     *
     * @mbggenerated
     */
    private String cusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.serName
     *
     * @mbggenerated
     */
    private String sername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.INPUT_TIME
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.INPUT_USER
     *
     * @mbggenerated
     */
    private String inputUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sweep.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.ID
     *
     * @return the value of sweep.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.ID
     *
     * @param id the value for sweep.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.MEMBERID
     *
     * @return the value of sweep.MEMBERID
     *
     * @mbggenerated
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.MEMBERID
     *
     * @param memberid the value for sweep.MEMBERID
     *
     * @mbggenerated
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.cusName
     *
     * @return the value of sweep.cusName
     *
     * @mbggenerated
     */
    public String getCusname() {
        return cusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.cusName
     *
     * @param cusname the value for sweep.cusName
     *
     * @mbggenerated
     */
    public void setCusname(String cusname) {
        this.cusname = cusname == null ? null : cusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.phone
     *
     * @return the value of sweep.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.phone
     *
     * @param phone the value for sweep.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.serName
     *
     * @return the value of sweep.serName
     *
     * @mbggenerated
     */
    public String getSername() {
        return sername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.serName
     *
     * @param sername the value for sweep.serName
     *
     * @mbggenerated
     */
    public void setSername(String sername) {
        this.sername = sername == null ? null : sername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.INPUT_TIME
     *
     * @return the value of sweep.INPUT_TIME
     *
     * @mbggenerated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.INPUT_TIME
     *
     * @param inputTime the value for sweep.INPUT_TIME
     *
     * @mbggenerated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.INPUT_USER
     *
     * @return the value of sweep.INPUT_USER
     *
     * @mbggenerated
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.INPUT_USER
     *
     * @param inputUser the value for sweep.INPUT_USER
     *
     * @mbggenerated
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.UPDATE_TIME
     *
     * @return the value of sweep.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.UPDATE_TIME
     *
     * @param updateTime the value for sweep.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sweep.UPDATE_USER
     *
     * @return the value of sweep.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sweep.UPDATE_USER
     *
     * @param updateUser the value for sweep.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String name;
}