package com.dqbz.dao;

import com.dqbz.model.Association;

public interface AssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int insert(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int insertSelective(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    Association selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Association record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AssociationService
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Association record);
}