package com.dqbz.dao;

import com.dqbz.model.Sir;

public interface SirMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int insert(Sir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int insertSelective(Sir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    Sir selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Sir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sir
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sir record);
}