package com.dqbz.model;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.INPUT_TIME
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.INPUT_USER
     *
     * @mbggenerated
     */
    private String inputUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.ID
     *
     * @return the value of news.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.ID
     *
     * @param id the value for news.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.TITLE
     *
     * @return the value of news.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.TITLE
     *
     * @param title the value for news.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.INPUT_TIME
     *
     * @return the value of news.INPUT_TIME
     *
     * @mbggenerated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.INPUT_TIME
     *
     * @param inputTime the value for news.INPUT_TIME
     *
     * @mbggenerated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.INPUT_USER
     *
     * @return the value of news.INPUT_USER
     *
     * @mbggenerated
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.INPUT_USER
     *
     * @param inputUser the value for news.INPUT_USER
     *
     * @mbggenerated
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.UPDATE_TIME
     *
     * @return the value of news.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.UPDATE_TIME
     *
     * @param updateTime the value for news.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.UPDATE_USER
     *
     * @return the value of news.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.UPDATE_USER
     *
     * @param updateUser the value for news.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.CONTENT
     *
     * @return the value of news.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.CONTENT
     *
     * @param content the value for news.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}