package com.dqbz.dao;

import com.dqbz.model.Sweep;

import java.util.List;

public interface SweepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    int insert(Sweep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    int insertSelective(Sweep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    Sweep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sweep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sweep
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sweep record);

    List<Sweep> selectAllSweep();

}